### ISSUE TITLE
Blog features

### ISSUE THREAD

**Issue by 3kynox** [kirschbaum/laravel-spark-pages#5]
Hey there !

I ask this because I just saw blog posts writed in README file but i found no more references about this : 

Does laravel-spark-pages can manage blog post adding / removing / editing beside of pages feature ?

I mean, a blog area have to be inside a new created page and be able to receive blog posts in it.

Anything about this ? If no, any plans for the future ?

Thanks anyway.

**Comment by kirschbaum** [comment]
@3kynox Yes, you could use this as a base for a blog if you wanted. It's missing some of the normal things you would find in a blog, like tagging, author relationships, search, etc. But it can be used as rudimentary blog to get you going.
