### ISSUE TITLE
Update to Spark 3.x?

### ISSUE THREAD

**Issue by ux-engineer** [kirschbaum/laravel-spark-pages#8]
Doc says this is under active development but no new commits in five months, when would Spark 3.x support come?

**Comment by dccampbell** [comment]
And now [v4 as well](https://spark.laravel.com/docs/4.0/upgrade). cc @kirschbaum

**Comment by kirschbaum** [comment]
Thanks @envision and @dccampbell. Documentation updated. Both are now supported.

**Comment by ux-engineer** [comment]
Thanks @kirschbaum, I'll be keeping an eye on this project for new Spark based projects at a later time!
